name: Pulumi

on:
  - pull_request

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn
          cache-dependency-path: yarn.lock

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: ${{ github.run_id }}

      - uses: hashicorp/vault-action@v2.4.0
        with:
          url: https://vault.wafflehacks.org
          method: jwt
          path: github-actions
          role: ${{ secrets.VAULT_ROLE }}
          jwtGithubAudience: https://github.com/WaffleHacks
          exportToken: true

      - run: yarn install
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: wafflehacks/infrastructure/prod
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          VAULT_ADDR: https://vault.wafflehacks.org
